# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Show.create(title: "Man Of The People", poster_url: "https://www.theatreinchicago.com/images/casting/Stage-Left-Theatre.jpg", company: "STAGE LEFT THEATRE", description: "MAN OF THE PEOPLE written by Dolores Diaz and directed by Anna C. Bahow: A charlatan doctor rises to power by pedaling a radical remedy in the days before medical regulation in the U.S")
# Show.create(title: "Panther in the Sky", poster_url: "https://www.theatreinchicago.com/images/casting/circa-pintig.jpg", company: "CIRCA PINTIG", description: "CIRCA Pintig is looking for actors for its Fall production of Panther in the Sky by Lani Montreal. Looking for African, Asian and Latino males ages 18-25 and females ages 30-45.")
# Show.create(title: "O'Brien & O'Brien", poster_url: "https://www.theatreinchicago.com/images/casting/galaxy-theater.jpg", company: "PARKER PLAYERS", description: "Description: We are thrilled that you are considering auditioning for Parker Players' production of Ripcord by David Lindsay-Abaire. Directed by Richard Dominick Non-equity. There is no participation fee. There is no pay/stipend. Auditions: Monday 8/15 6:00 pm - 7:30 pm and Tuesday 8/16 6:00 pm - 7:30 pm Audition Location: St. Michaels Church 647 Dundee Avenue Barrington, IL 60010. Auditions held in 'Sturtz House' (245 Sturtz Street Barrington, IL 60010) next to St. Michaels Church. Please park in church parking lot accessed off of Dundee Avenue. Callbacks: TBD by the director after auditions are concluded. Time Commitment: Rehearsals: Begin Monday, September 12th. Rehearsals: Monday-Thursday 6:30pm - 9:00pm. One weekend morning/afternoon per week. Schedule confirmed based on actors' conflicts. Tec Week: November 6th - November 10th Performances: Friday November 11th 7:30pm, Saturday November 12th 7:30pm, Sunday November 13th 2:30pm Performance Location: The Garlands Center for the Performing Arts (1000 Garlands Lane Barrington, IL 60010) Material To Prepare: What to Prepare for Auditions: Nothing. Just be yourself and show up. Actors may be asked to read from the script. Sides will be provided. Please bring headshot and resume IF you have them. Bring your calendar to list conflicts.")
# Show.create(title: "26 Pebbles", poster_url: "https://www.theatreinchicago.com/images/casting/generic.jpg", company: "MUNROE PARK THEATER GUILD", description: "The Chicago Park District's Munroe Park Theater Guild will hold auditions for their production of 26 PEBBLES by Eric Ulloa. MPTG is looking to cast 3 males and 4 females who can play multiple roles between the ages of 30 - 60. Auditions will be Monday, August 22nd and Wednesday, August 24th from 7:00 - 9:00 PM at Ridge Park - 9625 S. Longwood Drive. Chicago, IL 60643. Auditioners only need to attend one night of the open call and will be asked to give a cold reading from the script. Callbacks will be Friday, August 26th from 7:00 - 10:00 and rehearsals (M/W/F from 7:00 - 10:00) will begin September September 19th. 26 PEBBLES will be performed November 17th - 19th.")