User.create(username:"Aaron Wertheim", password:"a", password_confirmation:"a", role:"Casting Director")
User.create(username:"Leah Davis", password:"a", password_confirmation:"a", role:"Casting Director")
# User.create(username:"Paul Ling", password: "a", password_confirmation: "a", role: "Performer")
# User.create(username:"Justin Ramon", password: "a", password_confirmation: "a", role: "Performer")
# User.create(username:"Alex Wenner", password: "a", password_confirmation: "a", role: "Performer")
# User.create(username:"James Kyan", password: "a", password_confirmation: "a", role: "Performer")
# User.create(username:"Ian Murphy", password: "a", password_confirmation: "a", role: "Performer")
# User.create(username:"Lori Henderson", password: "a", password_confirmation: "a", role: "Performer")
# User.create(username:"Victor Zarour", password: "a", password_confirmation: "a", role: "Performer")
# User.create(username:"Joon Jung", password: "a", password_confirmation: "a", role: "Performer")




Show.create(title: "Man Of The People", poster_url: "https://www.theatreinchicago.com/images/casting/Stage-Left-Theatre.jpg", company: "STAGE LEFT THEATRE", description: "MAN OF THE PEOPLE written by Dolores Diaz and directed by Anna C. Bahow: A charlatan doctor rises to power by pedaling a radical remedy in the days before medical regulation in the U.S", user_id: 1)
Show.create(title: "Ripcord", poster_url: "https://www.theatreinchicago.com/images/casting/parker-players.jpg", company: "Parker Players", description: "We are thrilled that you are considering auditioning for Parker Players' production of Ripcord by David Lindsay-Abaire. Directed by Richard Dominick Non-equity. There is no participation fee. There is no pay/stipend. Auditions: Monday 8/15 6:00 pm - 7:30 pm and Tuesday 8/16 6:00 pm - 7:30 pm Audition Location: St. Michaels Church 647 Dundee Avenue Barrington, IL 60010. Auditions held in 'Sturtz House' (245 Sturtz Street Barrington, IL 60010) next to St. Michaels Church. Please park in church parking lot accessed off of Dundee Avenue. Callbacks: TBD by the director after auditions are concluded. Time Commitment: Rehearsals: Begin Monday, September 12th. Rehearsals: Monday-Thursday 6:30pm - 9:00pm. One weekend morning/afternoon per week. Schedule confirmed based on actors' conflicts. Tec Week: November 6th - November 10th Performances: Friday November 11th 7:30pm, Saturday November 12th 7:30pm, Sunday November 13th 2:30pm Performance Location: The Garlands Center for the Performing Arts (1000 Garlands Lane Barrington, IL 60010) Material To Prepare: What to Prepare for Auditions: Nothing. Just be yourself and show up. Actors may be asked to read from the script. Sides will be provided. Please bring headshot and resume IF you have them. Bring your calendar to list conflicts." , user_id: 1)
Show.create(title: "Ernani", poster_url: "https://www.theatreinchicago.com/images/theatre/lyricopera2.jpg", company: "Lyric Opera", description: "Urgent request for submission of photo, resume and 1-minute self-taped video introduction. This is an urgent notice due to a last minute change and rehearsals begin August 15th Lyric Opera is seeking Black or African American Actor to understudy the non- singing, non-speaking role of Ernani's father. This is a 7 week AGMA contract paying $581.00 per week. There is a $1000.00 initiation fee to join AGMA ($500.00 for AEA members) and $100.00 in yearly dues. Ernani's father is assassinated at the beginning of the opera and appears to Ernani at pivotal moments throughout the opera.  Please Note: Lyric requires everyone entering the building to be fully vaccinated. This includes receiving booster shots when eligible. You will be wearing a mask covering your mouth and nose at all times except in performance. If cast, you will need to provide a copy of your COVID-19 vaccination record.", user_id: 2)
Show.create(title: "Antigone", poster_url: "https://www.theatreinchicago.com/images/casting/playtime.jpg", company: "PlayTime Theatre Company", description: "Antigone written Sophocles and directed by Julie Szwedo: In the aftermath of a civil war in which the two sons of Oedipus, Eteocles and Polynieces, kill each other, the new king, Creon, tries to punish Polynieces for his disloyalty by not burying him properly. Antigone, the girl who will rise up alone and die young, decides to take fate into her own hands by directly disobeying Creon's law. The show will be done in the style of Baz Luhrmann's Romeo + Juliet with traditional classical language and modern music and setting. Antigone Character Breakdown: Eteocles (Male, 25-35) is the brother of Antigone, Ismene and Polyneices. He took control of Thebes after King Oedipus died, but then refused share the throne with his brother Polyneices. The two brothers fought and killed each other outside one of the city's seven gates - and that's when the real trouble began. Polyneices (Male, 25-35) is the brother of Antigone, Ismene and Eteocles. His name means 'many troubles', and he's generally remembered as 'the bad brother', because he attacked Thebes with a foreign army. While Eteocles was buried with full ritual honours, Polyneices was left as carrion for the crows, in punishment for the vile crime of assaulting his own city. Eurydice (Female, able to play 45+) is the wife of Creon (no relation to the other mythical Eurydice, the wife of Orpheus). She appears right at the end of the play Antigone, in profoundly wretched circumstances. Rehearsal and Audition Info: Rehearsals will be split between Olympia Park Field House in Edison Park, 60631 and second space TBA as needed. Schedule will be based around actor availability, looking at Thursdays, Fridays, and Sundays with a possible other weekday added as showtime approaches. ALL ACTORS MUST BE VACCINATED. Compensation will be share of profits split between cast and crew.", user_id: 1)
Show.create(title: "Big Fish", poster_url: "https://www.theatreinchicago.com/images/casting/dft-logo.jpg", company: "Deerfield Family Theater", description: "Deerfield Family Theater will be holding auditions for our fall production of Big Fish on August 24th, 25th, and 27th, with callbacks by invitation on August 28th. Performances are November 11-13, and November 18-20, 2022.", user_id: 2)
Show.create(title: "Comedy Team", poster_url: "https://www.theatreinchicago.com/images/casting/stir-friday-night.jpg", company: "Stir Friday Night", description: "Stir Friday Night, Chicago's longest-running Asian American comedy team, is holding auditions on August 22nd from 5:30-7:30 pm at the Annoyance, Studio F.", user_id: 1)
Show.create(title: "Stage Manager", poster_url: "https://www.theatreinchicago.com/images/casting/elsinore-players.jpg", company:"Elsinore Players", description:"Show: Who's Afraid of Virginia Woolf. Seeking: We are seeking a stage manager to round out our production staff for Who's Afraid of Virginia Woolf. Rehearsals are currently underway (Tuesday, Thursday, Sunday) and performances are September 9-25 at 7:00 pm on Friday, Saturday, and Sunday in Elgin, Illinois. There is a stipend.", user_id: 1)
Show.create(title: "2022 Season", poster_url: "https://www.theatreinchicago.com/images/casting/chicago-carolers.jpg", company: "The Chicago Carolers", description: "The Chicago Carolers are seeking new members to join us for the 2022 season! We are a group of professional singers and actors from the Chicagoland area. We sing carols of all kinds (traditional carols to modern favorites) in four-part harmony, and all of our carols are memorized. We dress in full Victorian costumes, and always bring a cheerful holiday spirit to events! We are currently looking for Sopranos, Altos, Tenors, and Basses to join our quartets.", user_id: 2)

puts "Seeding done"